/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.8-dev */

#ifndef PB_GLOBALDATA_PB_H_INCLUDED
#define PB_GLOBALDATA_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _GlobalData {
    uint32_t version;
    uint32_t songId;
} GlobalData;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define GlobalData_init_default                  {0, 0}
#define GlobalData_init_zero                     {0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define GlobalData_version_tag                   1
#define GlobalData_songId_tag                    2

/* Struct field encoding specification for nanopb */
#define GlobalData_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   version,           1) \
X(a, STATIC,   SINGULAR, UINT32,   songId,            2)
#define GlobalData_CALLBACK NULL
#define GlobalData_DEFAULT NULL

extern const pb_msgdesc_t GlobalData_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define GlobalData_fields &GlobalData_msg

/* Maximum encoded size of messages (where known) */
#define GlobalData_size                          12

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
