/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.8-dev */

#ifndef PB_PARAMLOCKPOOLINTERNAL_PB_H_INCLUDED
#define PB_PARAMLOCKPOOLINTERNAL_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _ParamLockPoolInternal {
    pb_callback_t locks;
    uint32_t freeLocks;
} ParamLockPoolInternal;

typedef struct _ParamLockPoolInternal_ParamLock {
    uint32_t index;
    uint8_t step;
    uint8_t param;
    uint8_t value;
    uint16_t next;
} ParamLockPoolInternal_ParamLock;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define ParamLockPoolInternal_init_default       {{{NULL}, NULL}, 0}
#define ParamLockPoolInternal_ParamLock_init_default {0, 0, 0, 0, 0}
#define ParamLockPoolInternal_init_zero          {{{NULL}, NULL}, 0}
#define ParamLockPoolInternal_ParamLock_init_zero {0, 0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define ParamLockPoolInternal_locks_tag          1
#define ParamLockPoolInternal_freeLocks_tag      2
#define ParamLockPoolInternal_ParamLock_index_tag 1
#define ParamLockPoolInternal_ParamLock_step_tag 2
#define ParamLockPoolInternal_ParamLock_param_tag 3
#define ParamLockPoolInternal_ParamLock_value_tag 4
#define ParamLockPoolInternal_ParamLock_next_tag 5

/* Struct field encoding specification for nanopb */
#define ParamLockPoolInternal_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  locks,             1) \
X(a, STATIC,   SINGULAR, UINT32,   freeLocks,         2)
#define ParamLockPoolInternal_CALLBACK pb_default_field_callback
#define ParamLockPoolInternal_DEFAULT NULL
#define ParamLockPoolInternal_locks_MSGTYPE ParamLockPoolInternal_ParamLock

#define ParamLockPoolInternal_ParamLock_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   index,             1) \
X(a, STATIC,   SINGULAR, UINT32,   step,              2) \
X(a, STATIC,   SINGULAR, UINT32,   param,             3) \
X(a, STATIC,   SINGULAR, UINT32,   value,             4) \
X(a, STATIC,   SINGULAR, UINT32,   next,              5)
#define ParamLockPoolInternal_ParamLock_CALLBACK NULL
#define ParamLockPoolInternal_ParamLock_DEFAULT NULL

extern const pb_msgdesc_t ParamLockPoolInternal_msg;
extern const pb_msgdesc_t ParamLockPoolInternal_ParamLock_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define ParamLockPoolInternal_fields &ParamLockPoolInternal_msg
#define ParamLockPoolInternal_ParamLock_fields &ParamLockPoolInternal_ParamLock_msg

/* Maximum encoded size of messages (where known) */
/* ParamLockPoolInternal_size depends on runtime parameters */
#define ParamLockPoolInternal_ParamLock_size     19

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
