// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ParamLockPoolInternal.proto

#include "ParamLockPoolInternal.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

PROTOBUF_CONSTEXPR ParamLockPoolInternal_ParamLock::ParamLockPoolInternal_ParamLock(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.index_)*/0u
  , /*decltype(_impl_.step_)*/0u
  , /*decltype(_impl_.param_)*/0u
  , /*decltype(_impl_.value_)*/0u
  , /*decltype(_impl_.next_)*/0u
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct ParamLockPoolInternal_ParamLockDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ParamLockPoolInternal_ParamLockDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ParamLockPoolInternal_ParamLockDefaultTypeInternal() {}
  union {
    ParamLockPoolInternal_ParamLock _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ParamLockPoolInternal_ParamLockDefaultTypeInternal _ParamLockPoolInternal_ParamLock_default_instance_;
PROTOBUF_CONSTEXPR ParamLockPoolInternal::ParamLockPoolInternal(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.locks_)*/{}
  , /*decltype(_impl_.freelocks_)*/0u
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct ParamLockPoolInternalDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ParamLockPoolInternalDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ParamLockPoolInternalDefaultTypeInternal() {}
  union {
    ParamLockPoolInternal _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ParamLockPoolInternalDefaultTypeInternal _ParamLockPoolInternal_default_instance_;
static ::_pb::Metadata file_level_metadata_ParamLockPoolInternal_2eproto[2];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_ParamLockPoolInternal_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_ParamLockPoolInternal_2eproto = nullptr;

const uint32_t TableStruct_ParamLockPoolInternal_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::ParamLockPoolInternal_ParamLock, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::ParamLockPoolInternal_ParamLock, _impl_.index_),
  PROTOBUF_FIELD_OFFSET(::ParamLockPoolInternal_ParamLock, _impl_.step_),
  PROTOBUF_FIELD_OFFSET(::ParamLockPoolInternal_ParamLock, _impl_.param_),
  PROTOBUF_FIELD_OFFSET(::ParamLockPoolInternal_ParamLock, _impl_.value_),
  PROTOBUF_FIELD_OFFSET(::ParamLockPoolInternal_ParamLock, _impl_.next_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::ParamLockPoolInternal, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::ParamLockPoolInternal, _impl_.locks_),
  PROTOBUF_FIELD_OFFSET(::ParamLockPoolInternal, _impl_.freelocks_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::ParamLockPoolInternal_ParamLock)},
  { 11, -1, -1, sizeof(::ParamLockPoolInternal)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::_ParamLockPoolInternal_ParamLock_default_instance_._instance,
  &::_ParamLockPoolInternal_default_instance_._instance,
};

const char descriptor_table_protodef_ParamLockPoolInternal_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\033ParamLockPoolInternal.proto\032\014nanopb.pr"
  "oto\"\315\001\n\025ParamLockPoolInternal\022/\n\005locks\030\001"
  " \003(\0132 .ParamLockPoolInternal.ParamLock\022\021"
  "\n\tfreeLocks\030\002 \001(\r\032p\n\tParamLock\022\r\n\005index\030"
  "\001 \001(\r\022\023\n\004step\030\002 \001(\rB\005\222\?\0028\010\022\024\n\005param\030\003 \001("
  "\rB\005\222\?\0028\010\022\024\n\005value\030\004 \001(\rB\005\222\?\0028\010\022\023\n\004next\030\005"
  " \001(\rB\005\222\?\0028\020b\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_ParamLockPoolInternal_2eproto_deps[1] = {
  &::descriptor_table_nanopb_2eproto,
};
static ::_pbi::once_flag descriptor_table_ParamLockPoolInternal_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_ParamLockPoolInternal_2eproto = {
    false, false, 259, descriptor_table_protodef_ParamLockPoolInternal_2eproto,
    "ParamLockPoolInternal.proto",
    &descriptor_table_ParamLockPoolInternal_2eproto_once, descriptor_table_ParamLockPoolInternal_2eproto_deps, 1, 2,
    schemas, file_default_instances, TableStruct_ParamLockPoolInternal_2eproto::offsets,
    file_level_metadata_ParamLockPoolInternal_2eproto, file_level_enum_descriptors_ParamLockPoolInternal_2eproto,
    file_level_service_descriptors_ParamLockPoolInternal_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_ParamLockPoolInternal_2eproto_getter() {
  return &descriptor_table_ParamLockPoolInternal_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_ParamLockPoolInternal_2eproto(&descriptor_table_ParamLockPoolInternal_2eproto);

// ===================================================================

class ParamLockPoolInternal_ParamLock::_Internal {
 public:
};

ParamLockPoolInternal_ParamLock::ParamLockPoolInternal_ParamLock(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:ParamLockPoolInternal.ParamLock)
}
ParamLockPoolInternal_ParamLock::ParamLockPoolInternal_ParamLock(const ParamLockPoolInternal_ParamLock& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  ParamLockPoolInternal_ParamLock* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.index_){}
    , decltype(_impl_.step_){}
    , decltype(_impl_.param_){}
    , decltype(_impl_.value_){}
    , decltype(_impl_.next_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.index_, &from._impl_.index_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.next_) -
    reinterpret_cast<char*>(&_impl_.index_)) + sizeof(_impl_.next_));
  // @@protoc_insertion_point(copy_constructor:ParamLockPoolInternal.ParamLock)
}

inline void ParamLockPoolInternal_ParamLock::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.index_){0u}
    , decltype(_impl_.step_){0u}
    , decltype(_impl_.param_){0u}
    , decltype(_impl_.value_){0u}
    , decltype(_impl_.next_){0u}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

ParamLockPoolInternal_ParamLock::~ParamLockPoolInternal_ParamLock() {
  // @@protoc_insertion_point(destructor:ParamLockPoolInternal.ParamLock)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ParamLockPoolInternal_ParamLock::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void ParamLockPoolInternal_ParamLock::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void ParamLockPoolInternal_ParamLock::Clear() {
// @@protoc_insertion_point(message_clear_start:ParamLockPoolInternal.ParamLock)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.index_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.next_) -
      reinterpret_cast<char*>(&_impl_.index_)) + sizeof(_impl_.next_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ParamLockPoolInternal_ParamLock::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint32 index = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.index_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 step = 2 [(.nanopb) = {
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.step_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 param = 3 [(.nanopb) = {
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.param_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 value = 4 [(.nanopb) = {
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _impl_.value_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 next = 5 [(.nanopb) = {
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 40)) {
          _impl_.next_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ParamLockPoolInternal_ParamLock::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ParamLockPoolInternal.ParamLock)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 index = 1;
  if (this->_internal_index() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(1, this->_internal_index(), target);
  }

  // uint32 step = 2 [(.nanopb) = {
  if (this->_internal_step() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(2, this->_internal_step(), target);
  }

  // uint32 param = 3 [(.nanopb) = {
  if (this->_internal_param() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(3, this->_internal_param(), target);
  }

  // uint32 value = 4 [(.nanopb) = {
  if (this->_internal_value() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(4, this->_internal_value(), target);
  }

  // uint32 next = 5 [(.nanopb) = {
  if (this->_internal_next() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(5, this->_internal_next(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ParamLockPoolInternal.ParamLock)
  return target;
}

size_t ParamLockPoolInternal_ParamLock::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ParamLockPoolInternal.ParamLock)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // uint32 index = 1;
  if (this->_internal_index() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_index());
  }

  // uint32 step = 2 [(.nanopb) = {
  if (this->_internal_step() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_step());
  }

  // uint32 param = 3 [(.nanopb) = {
  if (this->_internal_param() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_param());
  }

  // uint32 value = 4 [(.nanopb) = {
  if (this->_internal_value() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_value());
  }

  // uint32 next = 5 [(.nanopb) = {
  if (this->_internal_next() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_next());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ParamLockPoolInternal_ParamLock::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    ParamLockPoolInternal_ParamLock::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ParamLockPoolInternal_ParamLock::GetClassData() const { return &_class_data_; }


void ParamLockPoolInternal_ParamLock::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<ParamLockPoolInternal_ParamLock*>(&to_msg);
  auto& from = static_cast<const ParamLockPoolInternal_ParamLock&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ParamLockPoolInternal.ParamLock)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_index() != 0) {
    _this->_internal_set_index(from._internal_index());
  }
  if (from._internal_step() != 0) {
    _this->_internal_set_step(from._internal_step());
  }
  if (from._internal_param() != 0) {
    _this->_internal_set_param(from._internal_param());
  }
  if (from._internal_value() != 0) {
    _this->_internal_set_value(from._internal_value());
  }
  if (from._internal_next() != 0) {
    _this->_internal_set_next(from._internal_next());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ParamLockPoolInternal_ParamLock::CopyFrom(const ParamLockPoolInternal_ParamLock& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ParamLockPoolInternal.ParamLock)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ParamLockPoolInternal_ParamLock::IsInitialized() const {
  return true;
}

void ParamLockPoolInternal_ParamLock::InternalSwap(ParamLockPoolInternal_ParamLock* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ParamLockPoolInternal_ParamLock, _impl_.next_)
      + sizeof(ParamLockPoolInternal_ParamLock::_impl_.next_)
      - PROTOBUF_FIELD_OFFSET(ParamLockPoolInternal_ParamLock, _impl_.index_)>(
          reinterpret_cast<char*>(&_impl_.index_),
          reinterpret_cast<char*>(&other->_impl_.index_));
}

::PROTOBUF_NAMESPACE_ID::Metadata ParamLockPoolInternal_ParamLock::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_ParamLockPoolInternal_2eproto_getter, &descriptor_table_ParamLockPoolInternal_2eproto_once,
      file_level_metadata_ParamLockPoolInternal_2eproto[0]);
}

// ===================================================================

class ParamLockPoolInternal::_Internal {
 public:
};

ParamLockPoolInternal::ParamLockPoolInternal(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:ParamLockPoolInternal)
}
ParamLockPoolInternal::ParamLockPoolInternal(const ParamLockPoolInternal& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  ParamLockPoolInternal* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.locks_){from._impl_.locks_}
    , decltype(_impl_.freelocks_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.freelocks_ = from._impl_.freelocks_;
  // @@protoc_insertion_point(copy_constructor:ParamLockPoolInternal)
}

inline void ParamLockPoolInternal::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.locks_){arena}
    , decltype(_impl_.freelocks_){0u}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

ParamLockPoolInternal::~ParamLockPoolInternal() {
  // @@protoc_insertion_point(destructor:ParamLockPoolInternal)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ParamLockPoolInternal::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.locks_.~RepeatedPtrField();
}

void ParamLockPoolInternal::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void ParamLockPoolInternal::Clear() {
// @@protoc_insertion_point(message_clear_start:ParamLockPoolInternal)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.locks_.Clear();
  _impl_.freelocks_ = 0u;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ParamLockPoolInternal::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated .ParamLockPoolInternal.ParamLock locks = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_locks(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else
          goto handle_unusual;
        continue;
      // uint32 freeLocks = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.freelocks_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ParamLockPoolInternal::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ParamLockPoolInternal)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .ParamLockPoolInternal.ParamLock locks = 1;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_locks_size()); i < n; i++) {
    const auto& repfield = this->_internal_locks(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(1, repfield, repfield.GetCachedSize(), target, stream);
  }

  // uint32 freeLocks = 2;
  if (this->_internal_freelocks() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(2, this->_internal_freelocks(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ParamLockPoolInternal)
  return target;
}

size_t ParamLockPoolInternal::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ParamLockPoolInternal)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .ParamLockPoolInternal.ParamLock locks = 1;
  total_size += 1UL * this->_internal_locks_size();
  for (const auto& msg : this->_impl_.locks_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // uint32 freeLocks = 2;
  if (this->_internal_freelocks() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_freelocks());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ParamLockPoolInternal::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    ParamLockPoolInternal::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ParamLockPoolInternal::GetClassData() const { return &_class_data_; }


void ParamLockPoolInternal::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<ParamLockPoolInternal*>(&to_msg);
  auto& from = static_cast<const ParamLockPoolInternal&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ParamLockPoolInternal)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.locks_.MergeFrom(from._impl_.locks_);
  if (from._internal_freelocks() != 0) {
    _this->_internal_set_freelocks(from._internal_freelocks());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ParamLockPoolInternal::CopyFrom(const ParamLockPoolInternal& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ParamLockPoolInternal)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ParamLockPoolInternal::IsInitialized() const {
  return true;
}

void ParamLockPoolInternal::InternalSwap(ParamLockPoolInternal* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.locks_.InternalSwap(&other->_impl_.locks_);
  swap(_impl_.freelocks_, other->_impl_.freelocks_);
}

::PROTOBUF_NAMESPACE_ID::Metadata ParamLockPoolInternal::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_ParamLockPoolInternal_2eproto_getter, &descriptor_table_ParamLockPoolInternal_2eproto_once,
      file_level_metadata_ParamLockPoolInternal_2eproto[1]);
}

// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::ParamLockPoolInternal_ParamLock*
Arena::CreateMaybeMessage< ::ParamLockPoolInternal_ParamLock >(Arena* arena) {
  return Arena::CreateMessageInternal< ::ParamLockPoolInternal_ParamLock >(arena);
}
template<> PROTOBUF_NOINLINE ::ParamLockPoolInternal*
Arena::CreateMaybeMessage< ::ParamLockPoolInternal >(Arena* arena) {
  return Arena::CreateMessageInternal< ::ParamLockPoolInternal >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
