/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_SONGDATAINTERNAL_PB_H_INCLUDED
#define PB_SONGDATAINTERNAL_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _SongDataInternal {
    uint8_t changeLength[16];
    uint8_t syncIn;
    uint8_t syncOut;
    uint8_t bpm;
    uint8_t scale;
    uint8_t root;
    uint8_t delayTime;
    uint8_t delayFeedback;
    uint8_t playingPattern;
    uint8_t patternChain[16];
    uint8_t patternChainLength;
    uint8_t hpVol;
    uint8_t swing;
    /* optional so that songs written before the reverb had its own controls can be
 told apart from songs that genuinely store a zero, and fall back to the defaults */
    bool has_reverbFeedback;
    uint8_t reverbFeedback;
    bool has_reverbDamping;
    uint8_t reverbDamping;
    bool has_reverbModulation;
    uint8_t reverbModulation;
    /* which of the two feedback caps the top of the feedback knob reaches */
    bool has_reverbLowCap;
    uint8_t reverbLowCap;
} SongDataInternal;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define SongDataInternal_init_default            {{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 0, 0, 0, 0, 0, 0, 0, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 0, 0, 0, false, 0, false, 0, false, 0, false, 0}
#define SongDataInternal_init_zero               {{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 0, 0, 0, 0, 0, 0, 0, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 0, 0, 0, false, 0, false, 0, false, 0, false, 0}

/* Field tags (for use in manual encoding/decoding) */
#define SongDataInternal_changeLength_tag        1
#define SongDataInternal_syncIn_tag              2
#define SongDataInternal_syncOut_tag             3
#define SongDataInternal_bpm_tag                 4
#define SongDataInternal_scale_tag               6
#define SongDataInternal_root_tag                7
#define SongDataInternal_delayTime_tag           8
#define SongDataInternal_delayFeedback_tag       9
#define SongDataInternal_playingPattern_tag      10
#define SongDataInternal_patternChain_tag        11
#define SongDataInternal_patternChainLength_tag  12
#define SongDataInternal_hpVol_tag               13
#define SongDataInternal_swing_tag               14
#define SongDataInternal_reverbFeedback_tag      15
#define SongDataInternal_reverbDamping_tag       16
#define SongDataInternal_reverbModulation_tag    17
#define SongDataInternal_reverbLowCap_tag        18

/* Struct field encoding specification for nanopb */
#define SongDataInternal_FIELDLIST(X, a) \
X(a, STATIC,   FIXARRAY, UINT32,   changeLength,      1) \
X(a, STATIC,   SINGULAR, UINT32,   syncIn,            2) \
X(a, STATIC,   SINGULAR, UINT32,   syncOut,           3) \
X(a, STATIC,   SINGULAR, UINT32,   bpm,               4) \
X(a, STATIC,   SINGULAR, UINT32,   scale,             6) \
X(a, STATIC,   SINGULAR, UINT32,   root,              7) \
X(a, STATIC,   SINGULAR, UINT32,   delayTime,         8) \
X(a, STATIC,   SINGULAR, UINT32,   delayFeedback,     9) \
X(a, STATIC,   SINGULAR, UINT32,   playingPattern,   10) \
X(a, STATIC,   FIXARRAY, UINT32,   patternChain,     11) \
X(a, STATIC,   SINGULAR, UINT32,   patternChainLength,  12) \
X(a, STATIC,   SINGULAR, UINT32,   hpVol,            13) \
X(a, STATIC,   SINGULAR, UINT32,   swing,            14) \
X(a, STATIC,   OPTIONAL, UINT32,   reverbFeedback,   15) \
X(a, STATIC,   OPTIONAL, UINT32,   reverbDamping,    16) \
X(a, STATIC,   OPTIONAL, UINT32,   reverbModulation,  17) \
X(a, STATIC,   OPTIONAL, UINT32,   reverbLowCap,     18)
#define SongDataInternal_CALLBACK NULL
#define SongDataInternal_DEFAULT NULL

extern const pb_msgdesc_t SongDataInternal_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define SongDataInternal_fields &SongDataInternal_msg

/* Maximum encoded size of messages (where known) */
#define SONGDATAINTERNAL_PB_H_MAX_SIZE           SongDataInternal_size
#define SongDataInternal_size                    144

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
